[package]
name = "cdenv-cli"
description = "Host application library and cdenv command-line executable."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "cdenv"
path = "src/main.rs"

[dependencies]
bollard.workspace = true
cdenv-core.workspace = true
cdenv-devcontainer.workspace = true
clap.workspace = true
getrandom.workspace = true
hex.workspace = true
hmac.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
