//! Private workspace-scoped forwarding supervisor and control protocol.

use std::fs;
use std::io;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::os::unix::fs::PermissionsExt;
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::{Arc, RwLock};
use std::time::{Duration, Instant};

use cdenv_core::credential_broker::{
    BrokerFrameKind, CredentialLeaseIdentity, CredentialUserIdentity,
};
use cdenv_core::credential_protocol::GitCredentialRequest;
use cdenv_core::credentials::CredentialGrants;
use cdenv_core::{
    AgentBuildId, ContainerId, GenerationId, InstallationId, ProtocolVersion, WorkspaceName,
};
use getrandom::fill;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use tokio::io::{AsyncBufReadExt, AsyncReadExt, AsyncWriteExt, BufReader};
use tokio::net::{TcpListener, TcpStream, UnixListener, UnixStream};

use crate::agent_artifacts::AgentArtifactProvider;
use crate::bollard::{GENERATION_LABEL, INSTALLATION_LABEL, WORKSPACE_LABEL};
use crate::{
    BOLLARD_CONTROL_TIMEOUT, BollardAdapter, BrokerBackendError, BrokerBackendFuture,
    BrokerByteStream, CancellationToken, CredentialBrokerBackend, DockerEndpoint, ExecCommand,
    ManagedMode, atomic_write, ensure_lock_file, ensure_private_directory,
    serve_host_credential_broker,
};
use crate::{LockBehavior, LockGuard, LockMode};

/// Private host-supervisor protocol version.
pub const FORWARDING_SUPERVISOR_PROTOCOL: u32 = 1;
/// Maximum bytes accepted for one private control message.
pub const MAXIMUM_CONTROL_MESSAGE_BYTES: u64 = 8 * 1024;
/// Bound used while waiting for detached supervisor readiness and control replies.
pub const SUPERVISOR_CONTROL_TIMEOUT: Duration = Duration::from_secs(5);
const MAXIMUM_DIAGNOSTIC_BYTES: usize = 4 * 1024;

/// One requested listener and container-side target.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SupervisorForward {
    /// Requested loopback port.
    pub requested_port: u16,
    /// Whether an occupied requested port is fatal.
    pub require_local_port: bool,
    /// Validated `localhost` or Compose service host.
    pub target_host: String,
    /// Nonzero target port.
    pub target_port: u16,
}

/// Configuration for one generation-scoped credential service lease.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SupervisorCredentialLease {
    /// Private workspace-record receipt.
    pub workspace_receipt: String,
    /// Effective numeric user selected and verified during provisioning.
    pub user: CredentialUserIdentity,
    /// Current positive grant revision.
    pub grant_revision: u64,
    /// Independently configured capabilities at lease startup.
    #[serde(default)]
    pub grants: CredentialGrants,
    /// Stable absolute container runtime directory for this user/generation.
    pub runtime_directory: String,
}

/// Complete private supervisor startup identity and transport manifest.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SupervisorManifest {
    /// Stable installation identity.
    pub installation: InstallationId,
    /// Exact workspace identity.
    pub workspace: WorkspaceName,
    /// Exact active generation.
    pub generation: GenerationId,
    /// Build identity of the starting host.
    pub host_build_id: AgentBuildId,
    /// Build identity verified from the installed agent.
    pub agent_build_id: AgentBuildId,
    /// Agent protocol verified during provisioning.
    pub agent_protocol: ProtocolVersion,
    /// Exact active primary container.
    pub container: ContainerId,
    /// Verified absolute agent path in the container.
    pub agent_path: String,
    /// Exact local Docker Unix socket selected by the starter.
    pub docker_socket: PathBuf,
    /// Private control socket.
    pub control_socket: PathBuf,
    /// Private identity/state file, also used as the startup manifest.
    pub state_file: PathBuf,
    /// Lifetime lock held by the supervisor process.
    pub lifetime_lock: PathBuf,
    /// Authentication secret generated by the starter.
    token: String,
    /// All listener requests, bound transactionally before readiness.
    pub forwards: Vec<SupervisorForward>,
    /// Separately owned credential transport, independent from forwarding listeners.
    #[serde(default)]
    pub credential_lease: Option<SupervisorCredentialLease>,
}

/// Persisted, authenticated live supervisor state.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SupervisorState {
    /// Installation identity.
    pub installation: InstallationId,
    /// Workspace identity.
    pub workspace: WorkspaceName,
    /// Active generation.
    pub generation: GenerationId,
    /// Host build identity.
    pub host_build_id: AgentBuildId,
    /// Agent build identity.
    pub agent_build_id: AgentBuildId,
    /// Agent protocol identity.
    pub agent_protocol: ProtocolVersion,
    /// Private protocol identity.
    pub supervisor_protocol: u32,
    /// Process ID is diagnostic only and is never signalled.
    pub pid: u32,
    /// Assigned loopback listener addresses.
    pub listeners: Vec<SocketAddr>,
    /// Exact credential lease identity, when its independent service was requested.
    #[serde(default)]
    pub credential_lease: Option<CredentialLeaseIdentity>,
    /// Secret used only over the private control socket.
    token: String,
}

/// Expected identity attached to every status or down request.
#[derive(Clone, Debug)]
pub struct SupervisorClaim<'a> {
    /// Installation identity.
    pub installation: &'a InstallationId,
    /// Workspace identity.
    pub workspace: &'a WorkspaceName,
    /// Active generation.
    pub generation: GenerationId,
    /// Current host build.
    pub host_build_id: &'a AgentBuildId,
    /// Provisioned agent build.
    pub agent_build_id: &'a AgentBuildId,
    /// Provisioned agent protocol.
    pub agent_protocol: ProtocolVersion,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
enum ControlCommand {
    Status,
    Down,
    Reconcile {
        revision: u64,
        grants: CredentialGrants,
    },
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct ControlRequest {
    command: ControlCommand,
    installation: InstallationId,
    workspace: WorkspaceName,
    generation: GenerationId,
    host_build_id: AgentBuildId,
    agent_build_id: AgentBuildId,
    agent_protocol: ProtocolVersion,
    supervisor_protocol: u32,
    token: String,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct ControlResponse {
    accepted: bool,
    state: Option<SupervisorState>,
    credential_revision: Option<u64>,
    error: Option<String>,
}

/// Supervisor startup, authentication, transport, or cleanup failure.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum ForwardingSupervisorError {
    /// A configured forwarding target is invalid.
    #[error("invalid forwarding target {host:?}:{port}")]
    InvalidTarget {
        /// Rejected host.
        host: String,
        /// Rejected port.
        port: u16,
    },
    /// A required local listener could not be bound.
    #[error("cannot bind required forwarding listener 127.0.0.1:{port}: {source}")]
    RequiredListener {
        /// Requested port.
        port: u16,
        /// Bind failure.
        #[source]
        source: io::Error,
    },
    /// A listener could not be bound, including its alternate port.
    #[error("cannot bind forwarding listener for requested port {port}: {source}")]
    Listener {
        /// Requested port.
        port: u16,
        /// Bind failure.
        #[source]
        source: io::Error,
    },
    /// A managed runtime object could not be prepared.
    #[error("cannot prepare forwarding supervisor runtime: {0}")]
    Runtime(String),
    /// The manifest does not match this host build or protocol.
    #[error("incompatible forwarding supervisor {field} identity")]
    Identity {
        /// Incompatible identity field.
        field: &'static str,
    },
    /// A private control request was rejected.
    #[error("forwarding supervisor rejected authenticated {operation} request: {reason}")]
    Rejected {
        /// Requested control operation.
        operation: &'static str,
        /// Safe rejection reason.
        reason: String,
    },
    /// Private control I/O failed or timed out.
    #[error("forwarding supervisor control failed: {0}")]
    Control(String),
    /// Detached process startup failed.
    #[error("cannot start detached forwarding supervisor: {0}")]
    Start(#[source] io::Error),
    /// Docker/container/agent transport failed.
    #[error("forwarding transport failed: {0}")]
    Transport(String),
}

impl SupervisorManifest {
    /// Creates a manifest with a fresh 256-bit private control token.
    ///
    /// # Errors
    ///
    /// Returns an entropy or target-validation error.
    #[expect(
        clippy::too_many_arguments,
        reason = "private supervisor identity is intentionally explicit"
    )]
    pub fn new(
        installation: InstallationId,
        workspace: WorkspaceName,
        generation: GenerationId,
        host_build_id: AgentBuildId,
        agent_build_id: AgentBuildId,
        agent_protocol: ProtocolVersion,
        container: ContainerId,
        agent_path: String,
        docker_socket: PathBuf,
        control_socket: PathBuf,
        state_file: PathBuf,
        lifetime_lock: PathBuf,
        forwards: Vec<SupervisorForward>,
    ) -> Result<Self, ForwardingSupervisorError> {
        for forward in &forwards {
            validate_target(&forward.target_host, forward.target_port)?;
        }
        validate_runtime_paths(&workspace, &control_socket, &state_file, &lifetime_lock)?;
        if !docker_socket.is_absolute() {
            return Err(ForwardingSupervisorError::Identity {
                field: "Docker endpoint",
            });
        }
        if !agent_path.starts_with('/') || agent_path.contains('\0') {
            return Err(ForwardingSupervisorError::Identity {
                field: "agent path",
            });
        }
        let mut token = [0_u8; 32];
        fill(&mut token).map_err(|error| {
            ForwardingSupervisorError::Runtime(format!("cannot generate control token: {error}"))
        })?;
        Ok(Self {
            installation,
            workspace,
            generation,
            host_build_id,
            agent_build_id,
            agent_protocol,
            container,
            agent_path,
            docker_socket,
            control_socket,
            state_file,
            lifetime_lock,
            token: hex::encode(token),
            forwards,
            credential_lease: None,
        })
    }

    /// Adds an independently configured credential lease; zero forwards remain valid.
    #[must_use]
    pub fn with_credential_lease(mut self, lease: SupervisorCredentialLease) -> Self {
        self.credential_lease = Some(lease);
        self
    }
}

/// Writes a private manifest, starts the current executable detached, and waits for authenticated readiness.
///
/// # Errors
///
/// Returns private-storage, process-start, timeout, or identity errors.
pub async fn start_detached_supervisor(
    manifest: &SupervisorManifest,
) -> Result<SupervisorState, ForwardingSupervisorError> {
    let runtime = manifest.state_file.parent().ok_or_else(|| {
        ForwardingSupervisorError::Runtime("state file has no runtime directory".to_owned())
    })?;
    ensure_private_directory(runtime)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    ensure_lock_file(&manifest.lifetime_lock)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    let bytes = serde_json::to_vec(manifest)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    atomic_write(&manifest.state_file, &bytes, ManagedMode::PrivateFile)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    let executable = std::env::current_exe().map_err(ForwardingSupervisorError::Start)?;
    Command::new(executable)
        .arg("__forwarding-supervisor")
        .arg(&manifest.state_file)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .process_group(0)
        .spawn()
        .map_err(ForwardingSupervisorError::Start)?;

    let claim = claim_from_manifest(manifest);
    let deadline = Instant::now() + SUPERVISOR_CONTROL_TIMEOUT;
    loop {
        match supervisor_status(&manifest.control_socket, &manifest.token, &claim).await {
            Ok(state) => return Ok(state),
            Err(_) if Instant::now() < deadline => {
                tokio::time::sleep(Duration::from_millis(25)).await;
            }
            Err(error) => return Err(error),
        }
    }
}

/// Runs the private supervisor process from its private startup manifest.
///
/// This is an internal executable protocol, not a public V1 command.
///
/// # Errors
///
/// Returns manifest, identity, listener, Docker transport setup, or control errors.
pub async fn run_private_supervisor_manifest(path: &Path) -> Result<(), ForwardingSupervisorError> {
    let bytes =
        fs::read(path).map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    let manifest: SupervisorManifest = serde_json::from_slice(&bytes)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    if path != manifest.state_file {
        return Err(ForwardingSupervisorError::Identity {
            field: "workspace root",
        });
    }
    run_supervisor(manifest).await
}

async fn run_supervisor(manifest: SupervisorManifest) -> Result<(), ForwardingSupervisorError> {
    validate_manifest_identity(&manifest)?;
    let _lifetime = LockGuard::acquire(
        &manifest.lifetime_lock,
        LockMode::Exclusive,
        LockBehavior::FailFast,
    )
    .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    if manifest.control_socket.exists() {
        return Err(ForwardingSupervisorError::Runtime(
            "control socket already exists; refusing unverified replacement".to_owned(),
        ));
    }
    let _cleanup = SupervisorRuntimeCleanup {
        socket: manifest.control_socket.clone(),
        state: manifest.state_file.clone(),
    };
    let listeners = bind_listeners(&manifest.forwards).await?;
    let control = UnixListener::bind(&manifest.control_socket)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    fs::set_permissions(&manifest.control_socket, fs::Permissions::from_mode(0o600))
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;

    let state = SupervisorState {
        installation: manifest.installation.clone(),
        workspace: manifest.workspace.clone(),
        generation: manifest.generation,
        host_build_id: manifest.host_build_id.clone(),
        agent_build_id: manifest.agent_build_id.clone(),
        agent_protocol: manifest.agent_protocol,
        supervisor_protocol: FORWARDING_SUPERVISOR_PROTOCOL,
        pid: std::process::id(),
        listeners: listeners
            .iter()
            .map(TcpListener::local_addr)
            .collect::<Result<Vec<_>, _>>()
            .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?,
        credential_lease: manifest
            .credential_lease
            .as_ref()
            .map(|lease| credential_identity(&manifest, lease))
            .transpose()?,
        token: manifest.token.clone(),
    };
    persist_state(&manifest.state_file, &state)?;

    let endpoint = DockerEndpoint::from_verified_socket(manifest.docker_socket.clone())
        .map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))?;
    let connector = endpoint
        .bollard_connector(BOLLARD_CONTROL_TIMEOUT)
        .map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))?;
    let adapter = BollardAdapter::from_connector(&connector);

    let credential_backend = state
        .credential_lease
        .clone()
        .zip(manifest.credential_lease.as_ref())
        .map(|(identity, lease)| {
            Arc::new(LiveCredentialBackend::new(identity, lease.grants.clone()))
        });
    let mut accepts = tokio::task::JoinSet::new();
    if let (Some(lease), Some(backend)) = (
        manifest.credential_lease.clone(),
        credential_backend.clone(),
    ) {
        let adapter = adapter.clone();
        let manifest = manifest.clone();
        accepts.spawn(async move {
            run_credential_exec(adapter, &manifest, &lease, backend)
                .await
                .map_err(|error| io::Error::other(error.to_string()))
        });
    }
    for (listener, forward) in listeners.into_iter().zip(manifest.forwards.iter().cloned()) {
        let adapter = adapter.clone();
        let manifest = manifest.clone();
        accepts.spawn(async move {
            loop {
                let (stream, _) = listener.accept().await?;
                let adapter = adapter.clone();
                let manifest = manifest.clone();
                let forward = forward.clone();
                tokio::spawn(async move {
                    let _ = forward_connection(adapter, &manifest, &forward, stream).await;
                });
            }
            #[allow(unreachable_code)]
            Ok::<(), io::Error>(())
        });
    }

    let result = control_loop(&control, &state, credential_backend.as_ref()).await;
    accepts.abort_all();
    while accepts.join_next().await.is_some() {}
    result
}

struct SupervisorRuntimeCleanup {
    socket: PathBuf,
    state: PathBuf,
}

impl Drop for SupervisorRuntimeCleanup {
    fn drop(&mut self) {
        let _ = fs::remove_file(&self.socket);
        let _ = fs::remove_file(&self.state);
    }
}

async fn forward_connection(
    adapter: BollardAdapter,
    manifest: &SupervisorManifest,
    forward: &SupervisorForward,
    stream: TcpStream,
) -> Result<(), ForwardingSupervisorError> {
    let inspection = adapter
        .inspect_container(&manifest.container)
        .await
        .map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))?;
    verify_container(&inspection, manifest)?;
    let command = vec![
        manifest.agent_path.clone(),
        "forwarding-bridge".to_owned(),
        forward.target_host.clone(),
        forward.target_port.to_string(),
        manifest.agent_build_id.to_string(),
        manifest.agent_protocol.to_string(),
    ];
    let exec = adapter
        .create_attached_exec(
            &ExecCommand {
                container: &manifest.container,
                command: &command,
                user: None,
                working_directory: None,
                environment: &[],
            },
            true,
        )
        .await
        .map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))?;
    let (mut input, mut output) = stream.into_split();
    let mut diagnostics = BoundedDiagnostics::default();
    adapter
        .run_attached_exec(
            &exec,
            &mut input,
            &mut output,
            &mut diagnostics,
            &CancellationToken::default(),
        )
        .await
        .map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))
}

fn credential_identity(
    manifest: &SupervisorManifest,
    lease: &SupervisorCredentialLease,
) -> Result<CredentialLeaseIdentity, ForwardingSupervisorError> {
    if !lease.runtime_directory.starts_with('/') || lease.runtime_directory.contains('\0') {
        return Err(ForwardingSupervisorError::Identity {
            field: "credential runtime path",
        });
    }
    let identity = CredentialLeaseIdentity {
        installation: manifest.installation.clone(),
        workspace: manifest.workspace.clone(),
        workspace_receipt: lease.workspace_receipt.clone(),
        container: manifest.container.clone(),
        generation: manifest.generation,
        user: lease.user,
        host_build: manifest.host_build_id.clone(),
        agent_build: manifest.agent_build_id.clone(),
        agent_protocol: manifest.agent_protocol,
        broker_protocol: cdenv_core::credential_broker::CREDENTIAL_BROKER_PROTOCOL,
        grant_revision: lease.grant_revision,
    };
    identity
        .validate()
        .map_err(|_| ForwardingSupervisorError::Identity {
            field: "credential lease",
        })?;
    Ok(identity)
}

#[derive(Clone)]
struct LiveCredentialPolicy {
    revision: u64,
    grants: CredentialGrants,
    https_epoch: u64,
    agent_epoch: u64,
    identity_epoch: u64,
}

/// Supervisor-owned live authority. The lock contains no credential values and
/// is changed only after an authenticated control request.
struct LiveCredentialBackend {
    lease: CredentialLeaseIdentity,
    policy: RwLock<LiveCredentialPolicy>,
}

impl LiveCredentialBackend {
    fn new(lease: CredentialLeaseIdentity, grants: CredentialGrants) -> Self {
        Self {
            policy: RwLock::new(LiveCredentialPolicy {
                revision: lease.grant_revision,
                grants,
                https_epoch: lease.grant_revision,
                agent_epoch: lease.grant_revision,
                identity_epoch: lease.grant_revision,
            }),
            lease,
        }
    }

    fn reconcile(&self, revision: u64, grants: CredentialGrants) -> Result<u64, &'static str> {
        grants.validate().map_err(|_| "invalid credential grants")?;
        if revision == 0 {
            return Err("invalid credential revision");
        }
        let mut policy = self
            .policy
            .write()
            .map_err(|_| "credential authority unavailable")?;
        if revision < policy.revision || (revision == policy.revision && grants != policy.grants) {
            return Err("stale or conflicting credential revision");
        }
        if policy.grants.https_origins() != grants.https_origins() {
            policy.https_epoch = revision;
        }
        if policy.grants.ssh_selector() != grants.ssh_selector() {
            policy.agent_epoch = revision;
        }
        if policy
            .grants
            .enabled(cdenv_core::credentials::CredentialCapability::GitIdentity)
            != grants.enabled(cdenv_core::credentials::CredentialCapability::GitIdentity)
        {
            policy.identity_epoch = revision;
        }
        policy.revision = revision;
        policy.grants = grants;
        Ok(policy.revision)
    }

    fn revision(&self) -> Option<u64> {
        self.policy.read().ok().map(|policy| policy.revision)
    }

    fn exact_lease(&self, identity: &CredentialLeaseIdentity) -> bool {
        identity.installation == self.lease.installation
            && identity.workspace == self.lease.workspace
            && identity.workspace_receipt == self.lease.workspace_receipt
            && identity.container == self.lease.container
            && identity.generation == self.lease.generation
            && identity.user == self.lease.user
            && identity.host_build == self.lease.host_build
            && identity.agent_build == self.lease.agent_build
            && identity.agent_protocol == self.lease.agent_protocol
            && identity.broker_protocol == self.lease.broker_protocol
    }
}

impl CredentialBrokerBackend for LiveCredentialBackend {
    fn is_authorized(
        &self,
        identity: &CredentialLeaseIdentity,
        operation: BrokerFrameKind,
    ) -> bool {
        if !self.exact_lease(identity) {
            return false;
        }
        self.policy.read().is_ok_and(|policy| match operation {
            BrokerFrameKind::CredentialLookup => policy
                .grants
                .enabled(cdenv_core::credentials::CredentialCapability::GitHttps),
            BrokerFrameKind::AgentOpen => policy
                .grants
                .enabled(cdenv_core::credentials::CredentialCapability::SshAgent),
            BrokerFrameKind::IdentityRequest => policy
                .grants
                .enabled(cdenv_core::credentials::CredentialCapability::GitIdentity),
            _ => false,
        })
    }

    fn authorization_epoch(&self, operation: BrokerFrameKind) -> u64 {
        self.policy
            .read()
            .map_or(u64::MAX, |policy| match operation {
                BrokerFrameKind::CredentialLookup => policy.https_epoch,
                BrokerFrameKind::AgentOpen => policy.agent_epoch,
                BrokerFrameKind::IdentityRequest => policy.identity_epoch,
                _ => u64::MAX,
            })
    }

    fn credential_lookup(&self, body: Vec<u8>) -> BrokerBackendFuture<'_, Vec<u8>> {
        Box::pin(async move {
            let request = GitCredentialRequest::parse(&body).map_err(|_| BrokerBackendError)?;
            let allowed = self
                .policy
                .read()
                .is_ok_and(|policy| policy.grants.allows(request.origin()));
            if !allowed {
                return Err(BrokerBackendError);
            }
            // Production backend enrollment is composed by issue 77. Keeping
            // this value-free failure here is safer than claiming availability.
            Err(BrokerBackendError)
        })
    }

    fn connect_agent(&self) -> BrokerBackendFuture<'_, std::pin::Pin<Box<dyn BrokerByteStream>>> {
        Box::pin(async { Err(BrokerBackendError) })
    }

    fn identity_metadata(&self) -> BrokerBackendFuture<'_, Vec<u8>> {
        Box::pin(async { Err(BrokerBackendError) })
    }
}

async fn run_credential_exec(
    adapter: BollardAdapter,
    manifest: &SupervisorManifest,
    lease: &SupervisorCredentialLease,
    backend: Arc<LiveCredentialBackend>,
) -> Result<(), ForwardingSupervisorError> {
    let inspection = adapter
        .inspect_container(&manifest.container)
        .await
        .map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))?;
    verify_container(&inspection, manifest)?;
    let identity = credential_identity(manifest, lease)?;
    let command = vec![
        manifest.agent_path.clone(),
        "credential-bridge".to_owned(),
        lease.runtime_directory.clone(),
    ];
    let selected_user = format!("{}:{}", lease.user.uid, lease.user.gid);
    let exec = adapter
        .create_attached_exec(
            &ExecCommand {
                container: &manifest.container,
                command: &command,
                user: Some(&selected_user),
                working_directory: None,
                environment: &[],
            },
            true,
        )
        .await
        .map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))?;
    let inspected = adapter
        .inspect_exec(exec.id())
        .await
        .map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))?;
    if inspected.container != manifest.container || inspected.running {
        return Err(ForwardingSupervisorError::Identity {
            field: "credential Exec target",
        });
    }

    let (protocol_input, mut docker_input) =
        tokio::io::duplex(cdenv_core::credential_broker::MAX_BROKER_QUEUED_BYTES);
    let (mut docker_output, protocol_output) =
        tokio::io::duplex(cdenv_core::credential_broker::MAX_BROKER_QUEUED_BYTES);
    let protocol = tokio::io::join(protocol_output, protocol_input);
    let cancellation = CancellationToken::default();
    let mut diagnostics = BoundedDiagnostics::default();
    let transport = adapter.run_attached_exec(
        &exec,
        &mut docker_input,
        &mut docker_output,
        &mut diagnostics,
        &cancellation,
    );
    let broker = serve_host_credential_broker(protocol, identity, backend);
    tokio::pin!(transport);
    tokio::pin!(broker);
    tokio::select! {
        result = &mut transport => result.map_err(|error| ForwardingSupervisorError::Transport(error.to_string())),
        result = &mut broker => {
            cancellation.cancel();
            result.map_err(|error| ForwardingSupervisorError::Transport(error.to_string()))
        }
    }
}

fn verify_container(
    inspection: &crate::ContainerInspection,
    manifest: &SupervisorManifest,
) -> Result<(), ForwardingSupervisorError> {
    let matches = inspection.running
        && inspection
            .labels
            .get(INSTALLATION_LABEL)
            .map(String::as_str)
            == Some(manifest.installation.as_str())
        && inspection.labels.get(WORKSPACE_LABEL).map(String::as_str)
            == Some(manifest.workspace.as_str())
        && inspection.labels.get(GENERATION_LABEL).map(String::as_str)
            == Some(manifest.generation.to_string().as_str());
    if matches {
        Ok(())
    } else {
        Err(ForwardingSupervisorError::Identity {
            field: "active container",
        })
    }
}

async fn bind_listeners(
    forwards: &[SupervisorForward],
) -> Result<Vec<TcpListener>, ForwardingSupervisorError> {
    let mut listeners = Vec::with_capacity(forwards.len());
    for forward in forwards {
        let requested = SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), forward.requested_port);
        match TcpListener::bind(requested).await {
            Ok(listener) => listeners.push(listener),
            Err(source) if forward.require_local_port => {
                return Err(ForwardingSupervisorError::RequiredListener {
                    port: forward.requested_port,
                    source,
                });
            }
            Err(_) => listeners.push(TcpListener::bind((Ipv4Addr::LOCALHOST, 0)).await.map_err(
                |source| ForwardingSupervisorError::Listener {
                    port: forward.requested_port,
                    source,
                },
            )?),
        }
    }
    Ok(listeners)
}

async fn control_loop(
    listener: &UnixListener,
    state: &SupervisorState,
    credential_backend: Option<&Arc<LiveCredentialBackend>>,
) -> Result<(), ForwardingSupervisorError> {
    loop {
        let (stream, _) = listener
            .accept()
            .await
            .map_err(|error| ForwardingSupervisorError::Control(error.to_string()))?;
        if handle_control(stream, state, credential_backend).await? {
            return Ok(());
        }
    }
}

async fn handle_control(
    stream: UnixStream,
    state: &SupervisorState,
    credential_backend: Option<&Arc<LiveCredentialBackend>>,
) -> Result<bool, ForwardingSupervisorError> {
    let mut reader = BufReader::new(stream);
    let mut bytes = Vec::new();
    let read = (&mut reader)
        .take(MAXIMUM_CONTROL_MESSAGE_BYTES + 1)
        .read_until(b'\n', &mut bytes)
        .await
        .map_err(|error| ForwardingSupervisorError::Control(error.to_string()))?;
    let parsed = if read as u64 > MAXIMUM_CONTROL_MESSAGE_BYTES || !bytes.ends_with(b"\n") {
        None
    } else {
        serde_json::from_slice::<ControlRequest>(&bytes).ok()
    };
    let (accepted, down, credential_revision, error) = match parsed {
        Some(request) if request_matches(&request, state) => match request.command {
            ControlCommand::Status => (
                true,
                false,
                credential_backend.and_then(|backend| backend.revision()),
                None,
            ),
            ControlCommand::Down => (true, true, None, None),
            ControlCommand::Reconcile { revision, grants } => match credential_backend {
                Some(backend) => match backend.reconcile(revision, grants) {
                    Ok(acknowledged) => (true, false, Some(acknowledged), None),
                    Err(reason) => (false, false, None, Some(reason.to_owned())),
                },
                None if grants.is_empty() => (true, false, Some(revision), None),
                None => (
                    false,
                    false,
                    None,
                    Some("credential transport is not enrolled; run cdenv up".to_owned()),
                ),
            },
        },
        _ => (
            false,
            false,
            None,
            Some("identity or authentication mismatch".to_owned()),
        ),
    };
    let response = ControlResponse {
        accepted,
        state: accepted.then(|| state.clone()),
        credential_revision,
        error,
    };
    let mut encoded = serde_json::to_vec(&response)
        .map_err(|error| ForwardingSupervisorError::Control(error.to_string()))?;
    encoded.push(b'\n');
    reader
        .get_mut()
        .write_all(&encoded)
        .await
        .map_err(|error| ForwardingSupervisorError::Control(error.to_string()))?;
    Ok(down)
}

/// Queries a supervisor only after all scoped identities and its token match.
///
/// # Errors
///
/// Returns timeout, I/O, malformed response, or authentication errors.
pub async fn supervisor_status(
    socket: &Path,
    token: &str,
    claim: &SupervisorClaim<'_>,
) -> Result<SupervisorState, ForwardingSupervisorError> {
    control_request(socket, token, claim, ControlCommand::Status, "status").await
}

/// Returns authenticated supervisor state and the currently acknowledged
/// credential policy revision without probing any credential backend.
///
/// # Errors
///
/// Returns the same fail-closed control errors as [`supervisor_status`].
pub async fn supervisor_credential_status(
    socket: &Path,
    token: &str,
    claim: &SupervisorClaim<'_>,
) -> Result<(SupervisorState, Option<u64>), ForwardingSupervisorError> {
    let response = control_exchange(socket, token, claim, ControlCommand::Status, "status").await?;
    let state = response.state.ok_or_else(|| {
        ForwardingSupervisorError::Control("accepted response omitted state".to_owned())
    })?;
    Ok((state, response.credential_revision))
}

/// Atomically replaces live credential authority and returns only after the
/// exact supervisor acknowledges the durable policy revision.
///
/// # Errors
///
/// Rejects stale revisions, absent credential enrollment, identity mismatch,
/// malformed replies, and acknowledgement timeout.
pub async fn reconcile_supervisor_credentials(
    socket: &Path,
    token: &str,
    claim: &SupervisorClaim<'_>,
    revision: u64,
    grants: &CredentialGrants,
) -> Result<SupervisorState, ForwardingSupervisorError> {
    let command = ControlCommand::Reconcile {
        revision,
        grants: grants.clone(),
    };
    let response = control_exchange(socket, token, claim, command, "credential reconcile").await?;
    if response.credential_revision != Some(revision) {
        return Err(ForwardingSupervisorError::Control(
            "credential revision acknowledgement mismatch".to_owned(),
        ));
    }
    response.state.ok_or_else(|| {
        ForwardingSupervisorError::Control("accepted response omitted state".to_owned())
    })
}

/// Stops a supervisor through its authenticated control channel, never by PID.
///
/// # Errors
///
/// Returns timeout, I/O, malformed response, or authentication errors.
pub async fn stop_supervisor(
    socket: &Path,
    token: &str,
    claim: &SupervisorClaim<'_>,
) -> Result<SupervisorState, ForwardingSupervisorError> {
    control_request(socket, token, claim, ControlCommand::Down, "down").await
}

async fn control_request(
    socket: &Path,
    token: &str,
    claim: &SupervisorClaim<'_>,
    command: ControlCommand,
    operation: &'static str,
) -> Result<SupervisorState, ForwardingSupervisorError> {
    let response = control_exchange(socket, token, claim, command, operation).await?;
    response.state.ok_or_else(|| {
        ForwardingSupervisorError::Control("accepted response omitted state".to_owned())
    })
}

async fn control_exchange(
    socket: &Path,
    token: &str,
    claim: &SupervisorClaim<'_>,
    command: ControlCommand,
    operation: &'static str,
) -> Result<ControlResponse, ForwardingSupervisorError> {
    let request = ControlRequest {
        command,
        installation: claim.installation.clone(),
        workspace: claim.workspace.clone(),
        generation: claim.generation,
        host_build_id: claim.host_build_id.clone(),
        agent_build_id: claim.agent_build_id.clone(),
        agent_protocol: claim.agent_protocol,
        supervisor_protocol: FORWARDING_SUPERVISOR_PROTOCOL,
        token: token.to_owned(),
    };
    let future = async {
        let mut stream = UnixStream::connect(socket).await?;
        let mut bytes = serde_json::to_vec(&request).map_err(io::Error::other)?;
        bytes.push(b'\n');
        stream.write_all(&bytes).await?;
        let reader = BufReader::new(stream);
        let mut response = Vec::new();
        reader
            .take(MAXIMUM_CONTROL_MESSAGE_BYTES + 1)
            .read_until(b'\n', &mut response)
            .await?;
        if response.len() as u64 > MAXIMUM_CONTROL_MESSAGE_BYTES || !response.ends_with(b"\n") {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "invalid bounded response",
            ));
        }
        serde_json::from_slice::<ControlResponse>(&response).map_err(io::Error::other)
    };
    let response = tokio::time::timeout(SUPERVISOR_CONTROL_TIMEOUT, future)
        .await
        .map_err(|_| ForwardingSupervisorError::Control("request timed out".to_owned()))?
        .map_err(|error| ForwardingSupervisorError::Control(error.to_string()))?;
    if response.accepted {
        Ok(response)
    } else {
        Err(ForwardingSupervisorError::Rejected {
            operation,
            reason: response
                .error
                .unwrap_or_else(|| "request denied".to_owned()),
        })
    }
}

/// Loads a private state file and returns the token needed by an exact scoped claim.
///
/// # Errors
///
/// Rejects non-private files and malformed state.
pub fn load_supervisor_state(path: &Path) -> Result<SupervisorState, ForwardingSupervisorError> {
    let metadata = fs::metadata(path)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    if metadata.permissions().mode() & 0o077 != 0 {
        return Err(ForwardingSupervisorError::Runtime(
            "supervisor state is not private".to_owned(),
        ));
    }
    let bytes =
        fs::read(path).map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    serde_json::from_slice(&bytes)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))
}

/// Borrows the private control token after the state file was safely loaded.
#[must_use]
pub fn supervisor_control_token(state: &SupervisorState) -> &str {
    &state.token
}

fn validate_manifest_identity(
    manifest: &SupervisorManifest,
) -> Result<(), ForwardingSupervisorError> {
    let host = AgentArtifactProvider::embedded_identity().map_err(|_| {
        ForwardingSupervisorError::Identity {
            field: "host build",
        }
    })?;
    if host != manifest.host_build_id {
        return Err(ForwardingSupervisorError::Identity {
            field: "host build",
        });
    }
    if manifest.host_build_id != manifest.agent_build_id {
        return Err(ForwardingSupervisorError::Identity {
            field: "agent build",
        });
    }
    if manifest.agent_protocol.get() != 1 {
        return Err(ForwardingSupervisorError::Identity {
            field: "agent protocol",
        });
    }
    validate_runtime_paths(
        &manifest.workspace,
        &manifest.control_socket,
        &manifest.state_file,
        &manifest.lifetime_lock,
    )?;
    for forward in &manifest.forwards {
        validate_target(&forward.target_host, forward.target_port)?;
    }
    if let Some(lease) = &manifest.credential_lease {
        credential_identity(manifest, lease)?;
    }
    Ok(())
}

fn validate_runtime_paths(
    workspace: &WorkspaceName,
    control_socket: &Path,
    state_file: &Path,
    lifetime_lock: &Path,
) -> Result<(), ForwardingSupervisorError> {
    let runtime = state_file.parent();
    let valid = runtime.is_some()
        && control_socket.parent() == runtime
        && lifetime_lock.parent() == runtime
        && runtime
            .and_then(Path::file_name)
            .and_then(|name| name.to_str())
            == Some("runtime")
        && runtime
            .and_then(Path::parent)
            .and_then(Path::file_name)
            .and_then(|name| name.to_str())
            == Some(workspace.as_str());
    if valid {
        Ok(())
    } else {
        Err(ForwardingSupervisorError::Identity {
            field: "workspace root",
        })
    }
}

fn request_matches(request: &ControlRequest, state: &SupervisorState) -> bool {
    request.installation == state.installation
        && request.workspace == state.workspace
        && request.generation == state.generation
        && request.host_build_id == state.host_build_id
        && request.agent_build_id == state.agent_build_id
        && request.agent_protocol == state.agent_protocol
        && request.supervisor_protocol == state.supervisor_protocol
        && request.token == state.token
}

fn validate_target(host: &str, port: u16) -> Result<(), ForwardingSupervisorError> {
    let valid = port != 0
        && (host == "localhost"
            || (host.len() <= 253
                && !host.is_empty()
                && host.parse::<IpAddr>().is_err()
                && host.split('.').all(|label| {
                    !label.is_empty()
                        && label.len() <= 63
                        && !label.starts_with('-')
                        && !label.ends_with('-')
                        && label
                            .bytes()
                            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
                })));
    if valid {
        Ok(())
    } else {
        Err(ForwardingSupervisorError::InvalidTarget {
            host: host.to_owned(),
            port,
        })
    }
}

fn persist_state(path: &Path, state: &SupervisorState) -> Result<(), ForwardingSupervisorError> {
    let bytes = serde_json::to_vec(state)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))?;
    atomic_write(path, &bytes, ManagedMode::PrivateFile)
        .map_err(|error| ForwardingSupervisorError::Runtime(error.to_string()))
}

fn claim_from_manifest(manifest: &SupervisorManifest) -> SupervisorClaim<'_> {
    SupervisorClaim {
        installation: &manifest.installation,
        workspace: &manifest.workspace,
        generation: manifest.generation,
        host_build_id: &manifest.host_build_id,
        agent_build_id: &manifest.agent_build_id,
        agent_protocol: manifest.agent_protocol,
    }
}

#[derive(Default)]
struct BoundedDiagnostics {
    bytes: Vec<u8>,
}

impl tokio::io::AsyncWrite for BoundedDiagnostics {
    fn poll_write(
        mut self: std::pin::Pin<&mut Self>,
        _: &mut std::task::Context<'_>,
        buffer: &[u8],
    ) -> std::task::Poll<Result<usize, io::Error>> {
        let available = MAXIMUM_DIAGNOSTIC_BYTES.saturating_sub(self.bytes.len());
        self.bytes
            .extend_from_slice(&buffer[..buffer.len().min(available)]);
        std::task::Poll::Ready(Ok(buffer.len()))
    }

    fn poll_flush(
        self: std::pin::Pin<&mut Self>,
        _: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), io::Error>> {
        std::task::Poll::Ready(Ok(()))
    }

    fn poll_shutdown(
        self: std::pin::Pin<&mut Self>,
        _: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), io::Error>> {
        std::task::Poll::Ready(Ok(()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest(directory: &Path) -> SupervisorManifest {
        let build = AgentArtifactProvider::embedded_identity().expect("host build");
        SupervisorManifest::new(
            InstallationId::parse("installation-1").expect("installation"),
            WorkspaceName::parse("workspace").expect("workspace"),
            GenerationId::new(1).expect("generation"),
            build.clone(),
            build,
            ProtocolVersion::new(1).expect("protocol"),
            ContainerId::parse("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                .expect("container"),
            "/usr/local/bin/cdenv-agent".to_owned(),
            directory.join("docker.sock"),
            directory.join("supervisor.sock"),
            directory.join("supervisor.json"),
            directory.join(".supervisor.lock"),
            Vec::new(),
        )
        .expect("manifest")
    }

    #[test]
    fn target_validation_rejects_non_loopback_ip_and_zero_port() {
        assert!(validate_target("127.0.0.1", 80).is_err());
        assert!(validate_target("database", 0).is_err());
    }

    #[test]
    fn target_validation_accepts_container_and_compose_names() {
        assert!(validate_target("localhost", 3000).is_ok());
        assert!(validate_target("database.internal", 5432).is_ok());
    }

    #[tokio::test]
    async fn authenticated_control_reconciles_credentials_without_stopping_supervisor() {
        let temporary = tempfile::tempdir().expect("temporary directory");
        let workspace_root = temporary.path().join("workspace");
        fs::create_dir(&workspace_root).expect("workspace root");
        let runtime = workspace_root.join("runtime");
        ensure_private_directory(&runtime).expect("private runtime");
        let mut grants = CredentialGrants::default();
        grants.enable_identity();
        let manifest = manifest(&runtime).with_credential_lease(SupervisorCredentialLease {
            workspace_receipt: "0123456789abcdef0123456789abcdef".to_owned(),
            user: CredentialUserIdentity {
                uid: 1000,
                gid: 1000,
            },
            grant_revision: 1,
            grants,
            runtime_directory: "/tmp/cdenv-credential-test".to_owned(),
        });
        let _docker = std::os::unix::net::UnixListener::bind(&manifest.docker_socket)
            .expect("fake Docker socket");
        ensure_lock_file(&manifest.lifetime_lock).expect("lifetime lock");
        let claim_identity = manifest.clone();
        let claim = claim_from_manifest(&claim_identity);
        let socket = manifest.control_socket.clone();
        let token = manifest.token.clone();
        let task = tokio::spawn(run_supervisor(manifest));
        loop {
            if supervisor_status(&socket, &token, &claim).await.is_ok() {
                break;
            }
            tokio::time::sleep(Duration::from_millis(5)).await;
        }
        let before = supervisor_status(&socket, &token, &claim)
            .await
            .expect("status");
        reconcile_supervisor_credentials(&socket, &token, &claim, 2, &CredentialGrants::default())
            .await
            .expect("acknowledged revocation");
        let (after, revision) = supervisor_credential_status(&socket, &token, &claim)
            .await
            .expect("status after reconcile");
        assert_eq!(revision, Some(2));
        assert_eq!(after.listeners, before.listeners);
        assert!(
            reconcile_supervisor_credentials(
                &socket,
                &token,
                &claim,
                1,
                &CredentialGrants::default(),
            )
            .await
            .is_err()
        );
        stop_supervisor(&socket, &token, &claim)
            .await
            .expect("authenticated down");
        task.await.expect("supervisor task").expect("clean exit");
    }

    #[tokio::test]
    async fn supervisor_authenticates_status_and_down_without_pid_signalling() {
        let temporary = tempfile::tempdir().expect("temporary directory");
        let workspace_root = temporary.path().join("workspace");
        fs::create_dir(&workspace_root).expect("workspace root");
        let runtime = workspace_root.join("runtime");
        ensure_private_directory(&runtime).expect("private runtime");
        let manifest = manifest(&runtime);
        let _docker = std::os::unix::net::UnixListener::bind(&manifest.docker_socket)
            .expect("fake Docker socket");
        ensure_lock_file(&manifest.lifetime_lock).expect("lifetime lock");
        let claim_identity = manifest.clone();
        let claim = claim_from_manifest(&claim_identity);
        let socket = manifest.control_socket.clone();
        let token = manifest.token.clone();
        let task = tokio::spawn(run_supervisor(manifest));
        loop {
            if supervisor_status(&socket, &token, &claim).await.is_ok() {
                break;
            }
            tokio::time::sleep(Duration::from_millis(5)).await;
        }

        let denied = supervisor_status(&socket, "wrong-token", &claim).await;
        assert!(matches!(
            denied,
            Err(ForwardingSupervisorError::Rejected { .. })
        ));
        stop_supervisor(&socket, &token, &claim)
            .await
            .expect("authenticated down");
        task.await.expect("supervisor task").expect("clean exit");
    }
}
